
version: '3.5'
services:

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
     kafka_net:
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins2

  kafka_1:
    container_name: kafka_1
    hostname: kafka_1
    image: confluentinc/cp-kafka:latest
    ports:
      - target: 9091
        published: 9091
        protocol: tcp
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka_1:29091,OUTSIDE://:9091
      - KAFKA_LISTENERS=INSIDE://:29091,OUTSIDE://:9091
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
     kafka_net:
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins1

  python_producer_1:
    container_name: python_producer_1  
    image: python-kafka:latest
    stdin_open: true
    tty: true
    networks:
     kafka_net:
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins2

  python_consumer_1:
    container_name: python_consumer_1  
    image: python-kafka:latest
    stdin_open: true
    tty: true
    networks:
     kafka_net:
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins1

networks:
  kafka_net:
   name: kafka_net
