version: "3"
services:
  mqtt:
    image: eclipse-mosquitto:1.6.8
    container_name: mqtt 
    ports:
      - 8080:8080 
      - 1883:1883
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper 
  kafdrop:
    image: 'obsidiandynamics/kafdrop:latest'
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=PLAINTEXT://kafka:9092
  schema:
    image: confluentinc/cp-schema-registry:latest
    depends_on:
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: kafka
      SCHEMA_REGISTRY_LISTENERS: http://schema:8081

      
