version: '3.5'
services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins2
  kafka_1:
    container_name: kafka_1
    hostname: kafka_1
    image: confluentinc/cp-kafka:latest
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins2
  kafka_2:
    container_name: kafka_2
    hostname: kafka_2
    image: confluentinc/cp-kafka:latest
    ports:
      - target: 9093
        published: 9093
        protocol: tcp
        mode: host
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_2:9093,PLAINTEXT_HOST://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins1
