version: '3.5'
services:
    
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
     kafka_net:
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins2
  kafka_1:
    container_name: kafka_1
    hostname: kafka_1
    image: confluentinc/cp-kafka:latest
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka_1:29092,OUTSIDE://:9092
      - KAFKA_LISTENERS=INSIDE://:29092,OUTSIDE://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
     kafka_net:
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins2
  # kafka_2:
  #   container_name: kafka_2
  #   hostname: kafka_2
  #   image: confluentinc/cp-kafka:latest
  #   ports:
  #     - target: 9093
  #       published: 9093
  #       protocol: tcp
  #   depends_on:
  #     - zookeeper
  #     - kafka_1
  #   environment:
  #     - KAFKA_BROKER_ID=2
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka_2:29093,OUTSIDE://:9093
  #     - KAFKA_LISTENERS=INSIDE://:29093,OUTSIDE://:9093
  #     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
  #     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  #   networks:
  #    kafka_net:
  #   deploy:
  #     replicas: 1
  #     placement:    
  #       constraints:
  #         - node.labels.name==dtwins1
          
  python_producer:
    container_name: python_producer  
    image: python-kafka:latest
    stdin_open: true
    tty: true
    depends_on:
      - kafka_2
    networks:
     kafka_net:
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins1
          
  python_consumer:
    container_name: python_consumer
    image: python-kafka:latest
    depends_on:
      - python_producer
    stdin_open: true
    tty: true
    networks:
     kafka_net:
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins1
  
networks:
  kafka_net:
   name: kafka_net
  
