
version: '3.5'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      kafka_net:
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==dtwins1
# Producers and consumers =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  python_producer:
    image: python-kafka:latest
    stdin_open: true
    tty: true
    networks:
     kafka_net:
    deploy:
      replicas: 3
      placement:    
        constraints:
          - node.labels.kafka_role==producer_pair
  python_consumer:
    image: python-kafka:latest
    stdin_open: true
    tty: true
    networks:
     kafka_net:
    deploy:
      replicas: 3
      placement:    
        constraints:
          - node.labels.name==dtwins1
# MQTT (MQX) =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  etcd:
    image: 'bitnami/ctcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_ENABLE_V2=true
      - ETCDL_API=2
    networks:
      - kafka_net
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.name==dtwins1
  mqtt:
    image: "emqx/emqx:4.3.8"
    environment:
      - EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0
      - EMQX_ZONE__EXTERNAL__MAX_INFLIGHT=32
      - EMQX_CLUSTER__DISCOVERY=etcd
      - EMQX_CLUSTER__ETCD__SERVER=http://etcd:2379
      - EMQX_CLUSTER__ETCD__PREFIX=emqcl
      - EMQX_CLUSTER__ETCD__NODE_TTL=1m
      - EMQX_ZONE__EXTERNAL__MQUEUE_PRIORITIES=A/A/A=10,A/C/C=5
    networks:
      kafka_net:
    restart: always
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.kafka_role==kafka_node
# Kafka =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
     kafka_net:
    deploy:
      replicas: 0
      placement:
       constraints:
         - node.labels.kafka_role==kafka_node

networks:
  kafka_net:
   name: kafka_net
